#!/usr/bin/perl -w

    system ('pip install --upgrade bottle batinfo https://bitbucket.org/gleb_zhulik/py3sensors/get/tip.tar.gz zeroconf netifaces pymdstat influxdb statsd pystache Glances');
    system ('/sbin/e-smith/signal-event firewall-adjust');
