#!/usr/bin/perl -w

use esmith::ConfigDB;
my $db = esmith::ConfigDB->open_ro;
my $status = $db->get_prop('glances','status')|| 'disabled';

if ($status eq 'enabled') {
system ('/sbin/service glances restart');
}

else {
system ('/sbin/service glances stop');
}
